version: "3.7"

services:
  database_dtmoney:
    image: postgres
    container_name: database_dtmoney
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=database_dtmoney
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: dtmoney_api
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_dtmoney
    depends_on:
      - database_dtmoney


volumes:
  pgdata:
    driver: local
